#!/usr/bin/env python3
"""
06p_simulate_tbip_family.py
===========================
Build a 20-fold Monte Carlo over a TBIP-style DGP. The truth has
ideological positions that are CONSTANT across topics
(x_{a,k} = x_a for all k), generated by a regression on covariates
whose coefficients are also constant across topics
(iota_{k,j} = iota_j for all k). This is the natural opposite of the
DGP-family in 06n, where both x and iota are topic-varying.

Per replicate:
    - X drawn fresh per replicate (same prevalences, same N=99)
    - iota vector of length J drawn fresh:
        * c0_zero            : 0
        * c1_uniform_all     : +0.30 (deterministic)
        * c2_topic4          : random sign x U(0.5, 1.5)
        * c3_topic16         : random sign x U(0.5, 1.5)
        * c4_topic25         : random sign x U(0.5, 1.5)
      (the suffixes c2/c3/c4 are kept only for code-level compatibility
      with 06n; under TBIP truth all three covariates are active on all
      topics with the same signed magnitude across k)
    - ideal_a = X_a @ iota + eps_a, broadcast to ideal_{a,k} = ideal_a
      for all k (genuinely topic-constant ideal points)
    - counts ~ Poisson with fresh seed

Same beta/eta/theta nuisance parameters as 06l/06n
(from the original PolAn fit), so the topic-content side of the model
is identical to the existing simulation studies; only the ideal-point
DGP changes.

Output: data_simulation/sim_tbip_NN/  (NN = 01..20)
    clean/                drop-in for STBS, fully self-contained
    ground_truth/         X, iota_sim, ideal_sim, beta, eta, ...
    warm_start_truth/     symlinks to simdata_centered_design (shared
                          beta/theta Gamma posteriors)
    sim_meta.json         {rep_idx, master_seed, poisson_seed, ...}

Run:
    ./STBS_CAVI/venv_gpu/bin/python3 06p_simulate_tbip_family.py
        [--n-sims 20] [--seed-base 20260800]
"""
import os, json, shutil, argparse
import numpy as np
from scipy import sparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REVISION_BASE = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
STBS_CAVI_DIR = os.path.join(REVISION_BASE, "STBS_CAVI")
CLEAN_DIR_REAL = os.path.join(STBS_CAVI_DIR, "data", "hein-daily", "clean")

DEFAULT_BASE = os.path.join(
    REVISION_BASE, "originalPolAn_results", "fits",
    "TBIPhier_ideal_ak_Nreg_all_joint_varfam_K25", "params",
)

SIM_ROOT = os.path.join(SCRIPT_DIR, "data_simulation")
SHARED_WS = os.path.join(SIM_ROOT, "simdata_centered_design", "warm_start_truth")

# Design parameters — SAME 5-covariate structure as 06l/06n for code reuse
TOP_N_PER_TOPIC = 100
NUM_TOPICS = 25
NUM_COVS = 5
COV_LABELS = ["c0_zero", "c1_uniform_all", "c2_topic4",
              "c3_topic16", "c4_topic25"]
COV_PREVALENCE = [0.30, 0.50, 0.25, 0.40, 0.20]
IOTA_UNIFORM_VALUE = 0.30
IOTA_LOW = 0.50
IOTA_HIGH = 1.50
IDEAL_NOISE_SIGMA = 0.10


def _load_first(dirpath, bases):
    """Try multiple base-names and extensions (npy/csv); raise if none found."""
    import pandas as pd
    for base in bases:
        for ext in ("_final.npy", ".npy"):
            p = os.path.join(dirpath, f"{base}{ext}")
            if os.path.exists(p):
                return np.load(p)
        p = os.path.join(dirpath, f"{base}.csv")
        if os.path.exists(p):
            return pd.read_csv(p, index_col=0).to_numpy()
    raise FileNotFoundError(f"none of {bases} found in {dirpath}")


def load_base(base_dir):
    bshp = _load_first(base_dir, ["beta_shape", "beta_shp"])
    brte = _load_first(base_dir, ["beta_rate", "beta_rte"])
    tshp = _load_first(base_dir, ["theta_shape", "theta_shp"])
    trte = _load_first(base_dir, ["theta_rate", "theta_rte"])
    eta = _load_first(base_dir, ["eta_location", "eta_loc"])
    beta = (bshp / brte).astype(np.float32)
    theta = (tshp / trte).astype(np.float32)
    eta = eta.astype(np.float32)
    ai_path = os.path.join(base_dir, "all_author_indices.npy")
    if os.path.exists(ai_path):
        ai = np.load(ai_path)
    else:
        ai = np.load(os.path.join(CLEAN_DIR_REAL, "author_indices114.npy"))
    return beta, eta, theta, ai.astype(np.int32)


def make_X(N, prev, rng):
    X = np.zeros((N, NUM_COVS), dtype=np.float32)
    for j, p in enumerate(prev):
        X[:, j] = rng.binomial(1, p, N).astype(np.float32)
    return X


def make_iota_tbip(K, X, rng):
    """TBIP-style DGP: iota is CONSTANT across topics. We draw a single
    coefficient vector iota_l of length J once and broadcast to (K, J).

      c0_zero          : 0
      c1_uniform_all   : +0.30 (fixed across replicates)
      c2_topic4        : sign in {-1,+1} times U(0.5, 1.5), drawn fresh
      c3_topic16       : sign in {-1,+1} times U(0.5, 1.5), drawn fresh
      c4_topic25       : sign in {-1,+1} times U(0.5, 1.5), drawn fresh

    No sign-balancing per topic is required because iota does not vary
    with k. The labels c2/c3/c4 are retained for code-level consistency
    with the centered_design DGP-family, but under TBIP truth all three
    covariates are active on every topic with the same coefficient.
    """
    iota_vec = np.zeros(NUM_COVS, dtype=np.float32)
    iota_vec[1] = IOTA_UNIFORM_VALUE
    for j in (2, 3, 4):
        sign = float(rng.choice([-1.0, 1.0]))
        mag = float(rng.uniform(IOTA_LOW, IOTA_HIGH))
        iota_vec[j] = sign * mag

    iota = np.tile(iota_vec[None, :], (K, 1)).astype(np.float32)
    pattern = np.zeros((K, NUM_COVS), dtype=np.int32)
    pattern[:, 1:] = 1   # all but c0 are active on all topics

    active = {
        "c0_zero":         np.array([], dtype=np.int32),
        "c1_uniform_all":  np.arange(K),
        "c2_topic4":       np.arange(K),
        "c3_topic16":      np.arange(K),
        "c4_topic25":      np.arange(K),
    }
    n_active_per_cov = {
        "c2_topic4": K, "c3_topic16": K, "c4_topic25": K,
    }
    return iota, pattern, active, n_active_per_cov, iota_vec


def reduce_vocab_top_n(beta, eta, top_n):
    """Top-N words per topic, union -> reduced vocab (deterministic)."""
    K, V_full = beta.shape
    top_sets = [set(int(i) for i in np.argsort(beta[k])[::-1][:top_n])
                for k in range(K)]
    kept = np.array(sorted(set().union(*top_sets)), dtype=np.int64)
    return beta[:, kept], eta[:, kept], kept


def sample_dtm(theta, beta, eta, ideal, author_indices, rng):
    N = ideal.shape[0]
    D, K = theta.shape
    _, V = beta.shape
    eta_effect = np.exp(eta[None, :, :] * ideal[:, :, None]).astype(np.float32)
    CHUNK = 512
    rows, cols, vals = [], [], []
    for start in range(0, D, CHUNK):
        stop = min(start + CHUNK, D)
        a_idx = author_indices[start:stop]
        rate = np.einsum("bk,kv,bkv->bv", theta[start:stop],
                          beta, eta_effect[a_idx]).astype(np.float32)
        samp = rng.poisson(rate).astype(np.float32)
        nz_r, nz_c = np.nonzero(samp)
        if nz_r.size == 0:
            continue
        rows.append(nz_r + start); cols.append(nz_c)
        vals.append(samp[nz_r, nz_c])
    rows = np.concatenate(rows); cols = np.concatenate(cols)
    vals = np.concatenate(vals)
    return sparse.csr_matrix((vals, (rows, cols)), shape=(D, V))


def build_replicate(rep_idx, master_seed, poisson_seed,
                    beta_full, eta_full, theta, author_indices,
                    overwrite=False):
    out_dir = os.path.join(SIM_ROOT, f"sim_tbip_{rep_idx:02d}")
    if os.path.exists(out_dir) and not overwrite:
        raise FileExistsError(f"{out_dir} already exists")
    clean = os.path.join(out_dir, "clean")
    gt = os.path.join(out_dir, "ground_truth")
    ws = os.path.join(out_dir, "warm_start_truth")
    for d in (clean, gt, ws):
        os.makedirs(d, exist_ok=True)

    beta_red, eta_red, kept = reduce_vocab_top_n(beta_full, eta_full,
                                                  TOP_N_PER_TOPIC)
    V_new = beta_red.shape[1]

    rng = np.random.default_rng(master_seed)
    N = int(author_indices.max()) + 1
    K = NUM_TOPICS

    X = make_X(N, COV_PREVALENCE, rng)
    iota, pattern, active, n_active, iota_vec = make_iota_tbip(K, X, rng)

    # TBIP-style ideal: a single vector per author, broadcast across k.
    # ideal_a = X_a @ iota_vec + eps_a, then ideal_{a,k} = ideal_a for all k.
    ideal_a = (X @ iota_vec).astype(np.float32)
    eps_a = rng.normal(0, IDEAL_NOISE_SIGMA, ideal_a.shape).astype(np.float32)
    ideal_a = ideal_a + eps_a                               # (N,)
    ideal = np.tile(ideal_a[:, None], (1, K)).astype(np.float32)  # (N, K)

    rng_pois = np.random.default_rng(poisson_seed)
    counts = sample_dtm(theta, beta_red, eta_red, ideal, author_indices,
                         rng_pois)

    # ---------------- save GT ----------------
    np.save(os.path.join(gt, "iota_sim.npy"), iota)        # (K, J), all rows equal
    np.save(os.path.join(gt, "iota_sim_vec.npy"), iota_vec)# (J,) the underlying constant
    np.save(os.path.join(gt, "ideal_sim.npy"), ideal)      # (N, K), columns equal
    np.save(os.path.join(gt, "ideal_sim_vec.npy"), ideal_a)# (N,) the underlying constant
    np.save(os.path.join(gt, "X.npy"), X)
    np.save(os.path.join(gt, "beta.npy"), beta_red)
    np.save(os.path.join(gt, "eta.npy"), eta_red)
    np.save(os.path.join(gt, "theta.npy"), theta)
    np.save(os.path.join(gt, "author_indices.npy"), author_indices)
    np.save(os.path.join(gt, "effect_pattern.npy"), pattern)
    np.save(os.path.join(gt, "kept_word_indices.npy"), kept)

    meta = dict(
        rep_idx=rep_idx, master_seed=int(master_seed),
        poisson_seed=int(poisson_seed),
        dgp="tbip_constant_ideal",
        num_topics=int(K), num_covariates=int(NUM_COVS),
        num_authors=int(N),
        num_documents=int(theta.shape[0]),
        vocab_size_full=int(beta_full.shape[1]),
        vocab_size_reduced=int(V_new),
        iota_uniform_value=IOTA_UNIFORM_VALUE,
        iota_low=IOTA_LOW, iota_high=IOTA_HIGH,
        ideal_noise_sigma=IDEAL_NOISE_SIGMA,
        covariate_labels=COV_LABELS,
        covariate_prevalence=COV_PREVALENCE,
        active_topics={k: [int(x) for x in v] for k, v in active.items()},
        n_active_per_cov=n_active,
        iota_vec=[float(x) for x in iota_vec],
        notes=("TBIP-style DGP: ideal points x_{a,k} are CONSTANT across "
               "topics (x_a). The regression coefficients iota_{k,j} are "
               "also constant across topics (iota_j); only c0 is zero. "
               "Suffixes 'topic4 / topic16 / topic25' on c2 / c3 / c4 are "
               "code-level labels inherited from the DGP-family in 06n; "
               "under TBIP truth all five covariates have identical "
               "iota_j across all 25 topics. ideal_sim has shape (N, K) "
               "but every column is the same author-level scalar "
               "(stored separately as ideal_sim_vec.npy). Same beta/eta/"
               "theta from PolAn, shared warm-start posteriors via "
               "symlink."),
    )
    with open(os.path.join(gt, "simulation_meta.json"), "w") as fh:
        json.dump(meta, fh, indent=2)

    # ---------------- save clean ----------------
    sparse.save_npz(os.path.join(clean, "counts114.npz"), counts)
    np.save(os.path.join(clean, "author_indices114.npy"), author_indices)
    np.save(os.path.join(clean, "X_override.npy"), X)
    for fname in ("vocabulary114.txt",
                  "speech_id_indices114.npy",
                  "author_info114.csv",
                  "author_map114.txt",
                  "author_detailed_info114.csv",
                  "author_detailed_info_with_religion114.csv"):
        src = os.path.join(SIM_ROOT, "simdata_centered_design", "clean", fname)
        if os.path.exists(src):
            dst = os.path.join(clean, fname)
            if os.path.lexists(dst):
                os.remove(dst)
            try:
                os.symlink(os.path.relpath(src, clean), dst)
            except OSError:
                shutil.copy2(src, dst)

    # ---------------- warm-start (shared with centered-design) ----------------
    for fname in ("beta_shape_final.npy", "beta_rate_final.npy",
                  "theta_shape_final.npy", "theta_rate_final.npy"):
        src = os.path.join(SHARED_WS, fname)
        dst = os.path.join(ws, fname)
        if os.path.lexists(dst):
            os.remove(dst)
        try:
            os.symlink(os.path.relpath(src, ws), dst)
        except OSError:
            shutil.copy2(src, dst)

    return dict(rep_idx=rep_idx, master_seed=master_seed,
                poisson_seed=poisson_seed,
                counts_nnz=int(counts.nnz),
                counts_total=int(counts.sum()),
                X_prev=[round(float(X[:, j].mean()), 3)
                        for j in range(NUM_COVS)],
                ideal_mean=float(ideal_a.mean()),
                ideal_std=float(ideal_a.std()),
                iota_c2=float(iota_vec[2]),
                iota_c3=float(iota_vec[3]),
                iota_c4=float(iota_vec[4]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-sims", type=int, default=20)
    ap.add_argument("--seed-base", type=int, default=20260800,
                    help="master_seed_r = seed_base + 10*r,  "
                         "poisson_seed_r = master_seed_r + 1")
    ap.add_argument("--overwrite", action="store_true")
    ap.add_argument("--base-params-dir", default=DEFAULT_BASE)
    args = ap.parse_args()

    print("Loading PolAn nuisance parameters ...")
    beta, eta, theta, ai = load_base(args.base_params_dir)
    print(f"  beta: {beta.shape}, eta: {eta.shape}, theta: {theta.shape}")

    rows = []
    print(f"\nBuilding {args.n_sims} TBIP replicates from seed_base={args.seed_base}")
    for r in range(1, args.n_sims + 1):
        ms = args.seed_base + 10 * r
        ps = ms + 1
        print(f"\n  [sim_tbip_{r:02d}] master_seed={ms}, poisson_seed={ps}")
        meta = build_replicate(r, ms, ps, beta, eta, theta, ai,
                                overwrite=args.overwrite)
        rows.append(meta)
        print(f"    counts: nnz={meta['counts_nnz']:,}, total={meta['counts_total']:,}")
        print(f"    X prevalences: {meta['X_prev']}")
        print(f"    ideal: mean={meta['ideal_mean']:+.3f}, std={meta['ideal_std']:.3f}")
        print(f"    iota: c2={meta['iota_c2']:+.3f}, c3={meta['iota_c3']:+.3f}, "
              f"c4={meta['iota_c4']:+.3f}")

    import pandas as pd
    idx = pd.DataFrame(rows)
    idx_path = os.path.join(SIM_ROOT, "tbip_replicate_index.csv")
    idx.to_csv(idx_path, index=False)
    print(f"\nIndex written: {idx_path}")
    print(idx[["rep_idx","master_seed","counts_total",
                "ideal_mean","ideal_std",
                "iota_c2","iota_c3","iota_c4"]].to_string(index=False))


if __name__ == "__main__":
    main()
