#!/usr/bin/env python3
"""
20_misspec_constIP_table.py
===========================
Summarise the 20 per-replicate misspecification fits of S.7.1
(Truth = STBS topic-varying ideal points, Fit = TBIP-style constant
ideal point) as a single table, replacing the 20 per-replicate
forest plots. Reads the already-aggregated metrics; no re-compute.

Input : results_simulation/dgp_constIP_summary/global_replicate_metrics.csv
Output: results_simulation/dgp_constIP_summary/constIP_replicate_table.tex
"""
import os
import pandas as pd

REPO = os.path.dirname(os.path.abspath(__file__))
SUMM = os.path.join(REPO, "results_simulation", "dgp_constIP_summary")
CSV = os.path.join(SUMM, "global_replicate_metrics.csv")
OUT = os.path.join(SUMM, "constIP_replicate_table.tex")

EXEMPLARY = {7, 8}   # the two replicates shown as forest plots (worst + best)


def main():
    df = pd.read_csv(CSV).sort_values("rep").reset_index(drop=True)
    cols = ["cor_x_pearson_polmean", "cor_iota_l"]

    tex = ["% Auto-generated by 20_misspec_constIP_table.py"]
    tex.append(r"\begin{table}[H]")
    tex.append(r"\centering\small")
    tex.append(r"\caption{Recovery metrics for the misspecification study "
               r"of \S\ref{sec:misspec_down} (truth = STBS topic-varying "
               r"ideal points, fit = TBIP-style constant ideal point), "
               r"one row per Monte-Carlo replicate. "
               r"$r(\hat\ideal_a,\bar\ideal^{\mathrm{sim}}_a)$ is the "
               r"Pearson correlation, \emph{across the $99$ senators}, "
               r"between the fitted constant ideal point $\hat\ideal_a$ "
               r"and the $\theta$-weighted aggregate "
               r"$\bar\ideal^{\mathrm{sim}}_a=\sum_k w_{ak}\,"
               r"\ideal^{\mathrm{sim}}_{a,k}$ of the senator's true "
               r"topic-varying ideal points, using the same author "
               r"weights $w_{ak}\propto\sum_{d\in a}\mathbb{E}\theta_{dk}$ "
               r"as the headline aggregate of \S\ref{sec:dgp_oracle}; "
               r"$r(\hat\iota,\iota^{\mathrm{sim}})$ is the "
               r"regression-coefficient recovery. "
               r"Replicates \textbf{7} (weakest recovery) and \textbf{8} (strongest) are the two shown as "
               r"forest plots (Figures~\ref{fig:constIP_rep07}--\ref{fig:constIP_rep08}); "
               r"the remaining per-replicate forest plots are available "
               r"upon request.}")
    tex.append(r"\label{tab:constIP_replicates}")
    tex.append(r"\rowcolors{2}{gray!12}{white}")
    tex.append(r"\begin{tabular}{r c c}")
    tex.append(r"\toprule")
    tex.append(r"Rep & $r(\hat\ideal_a,\bar\ideal^{\mathrm{sim}}_a)$ & "
               r"$r(\hat\iota,\iota^{\mathrm{sim}})$ \\")
    tex.append(r"\midrule")
    for _, r in df.iterrows():
        rep = int(r["rep"])
        label = rf"\textbf{{{rep}}}" if rep in EXEMPLARY else f"{rep}"
        vals = " & ".join(f"{r[c]:.3f}" for c in cols)
        tex.append(f"{label} & {vals} \\\\")
    tex.append(r"\midrule")
    mean = " & ".join(f"{df[c].mean():.3f}" for c in cols)
    sd = " & ".join(f"{df[c].std(ddof=1):.3f}" for c in cols)
    tex.append(r"\textit{mean} & " + mean + r" \\")
    tex.append(r"\textit{sd} & " + sd + r" \\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    with open(OUT, "w") as fh:
        fh.write("\n".join(tex) + "\n")
    print(f"-> {OUT}  ({len(df)} replicates)")
    print(df[["rep"] + cols].round(3).to_string(index=False))


if __name__ == "__main__":
    main()
