#!/usr/bin/env python3
"""
22_misspec_tbip_recovery_table.py
=================================
Regenerate the TBIP-family ideal-point recovery table of S.7.2
(truth = TBIP-style constant ideal point, fit = STBS topic-varying)
from the aggregated metrics. Two-column layout (reps 1-10 | 11-20).
No re-compute of fits; reads the aggregation output.

Input : results_simulation/tbip_replicate_summary/global_replicate_metrics.csv
Output: results_simulation/tbip_replicate_summary/tbip_ideal_recovery_table.tex
"""
import os
import pandas as pd

REPO = os.path.dirname(os.path.abspath(__file__))
SUMM = os.path.join(REPO, "results_simulation", "tbip_replicate_summary")
CSV = os.path.join(SUMM, "global_replicate_metrics.csv")
OUT = os.path.join(SUMM, "tbip_ideal_recovery_table.tex")

EXEMPLARY = {9, 15}   # replicates shown as forest plots (best/worst iota)


def main():
    df = pd.read_csv(CSV).sort_values("rep").reset_index(drop=True)

    cap = (r"\caption{TBIP-family recovery, per replicate. For each of "
           r"the $20$ replicates: $r(\bar{\hat\ideal}_a,\ideal^{\mathrm{sim}}_a)$ "
           r"is the Pearson correlation between the $\theta$-weighted STBS "
           r"aggregate ideal point (author weights "
           r"$w_{ak}\propto\sum_{d\in a}\mathbb{E}\theta_{dk}$, the STBS "
           r"fit's own intensities, as in \S\ref{sec:dgp_oracle}) and "
           r"the constant TBIP truth; $r(\hat\iota,\iota^{\mathrm{sim}})$ "
           r"is the regression-coefficient recovery (flattened over all "
           r"$K\!\cdot\!J$ cells, the same quantity as in "
           r"Table~\ref{tab:constIP_replicates}); "
           r"$\overline{r}_k\pm\mathrm{sd}_k$ is the mean and standard "
           r"deviation, across the $25$ topics, of the per-topic "
           r"correlation between the topic-specific estimate and the "
           r"constant truth. A high aggregate and coefficient recovery "
           r"together with a high, low-variance $\overline{r}_k$ shows "
           r"that the over-parameterised topic-varying fit recovers the "
           r"constant truth on every topic rather than inventing spurious "
           r"topic-by-topic heterogeneity. Correlations are reported in "
           r"absolute value. Replicates \textbf{9} (strongest "
           r"coefficient recovery) and \textbf{15} (weakest) are the two "
           r"shown as forest plots "
           r"(Figures~\ref{fig:tbip_rep09}--\ref{fig:tbip_rep15}); the "
           r"remaining per-replicate forest plots are available upon "
           r"request.}")

    tex = ["% Auto-generated by 22_misspec_tbip_recovery_table.py"]
    tex.append(r"\begin{table}[H]")
    tex.append(r"\centering\small")
    tex.append(cap)
    tex.append(r"\label{tab:tbip_ideal_recovery}")
    tex.append(r"\rowcolors{2}{gray!12}{white}")
    tex.append(r"\begin{tabular}{r c c c}")
    tex.append(r"\toprule")
    tex.append(r"Rep & $r(\bar{\hat\ideal}_a,\ideal^{\mathrm{sim}}_a)$ & "
               r"$r(\hat\iota,\iota^{\mathrm{sim}})$ & "
               r"$\overline{r}_k\pm\mathrm{sd}_k$ \\")
    tex.append(r"\midrule")
    for _, r in df.iterrows():
        rep = int(r["rep"])
        lab = rf"\textbf{{{rep}}}" if rep in EXEMPLARY else f"{rep}"
        tex.append(f"{lab} & {r['cor_x_polmean_pearson']:.3f} & "
                   f"{r['cor_iota_flat']:.3f} & "
                   f"{r['mean_cor_per_topic']:.3f}\\,$\\pm$\\,"
                   f"{r['std_cor_per_topic']:.3f} \\\\")
    tex.append(r"\midrule")
    tex.append(r"\textit{mean} & "
               f"{df['cor_x_polmean_pearson'].mean():.3f} & "
               f"{df['cor_iota_flat'].mean():.3f} & "
               f"{df['mean_cor_per_topic'].mean():.3f} \\\\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    with open(OUT, "w") as fh:
        fh.write("\n".join(tex) + "\n")
    print(f"-> {OUT}")
    print(f"sign-flipped replicates: "
          f"{df[df.sign_flipped].rep.tolist() if 'sign_flipped' in df else 'n/a'}")
    print(f"r_agg mean {df.cor_x_polmean_pearson.mean():.3f}, "
          f"per-topic mean {df.mean_cor_per_topic.mean():.3f}")


if __name__ == "__main__":
    main()
