#!/usr/bin/env python3
"""
25_topic_dictionary.py
======================
Build the "topic dictionary" table requested by the referee (smaller comment
"Topic labeling" + the "organize the application section" suggestion):

    | Topic label | top terms (neutral) | ideal = -1 | ideal = +1 |

The three word columns are the *exact* construction underlying the paper's
word clouds (03_generate_wordclouds.py): per-topic neutral intensities
E[beta_kv] = beta_shape/beta_rate, shifted by the ideological factor
exp(eta_kv * ideal). Ranking each column by the corrected log-intensity
    log E[beta_kv] + ideal * eta_kv
reproduces the "Negative" (ideal=-1) and "Positive" (ideal=+1) word clouds
of Figure 4. The neutral column uses ideal = 0.

Orientation: eta_loc is stored in the paper's oriented frame (ideal > 0 =
Republican / conservative). This is verified against the manuscript's own
anchors: topic 13 (abortion) puts "unborn child / human life / feel pain"
at ideal=+1 and "womens health / birth control" at ideal=-1; topic 11
(climate) puts "entitled oversight" at +1 and "fossil fuel / carbon
pollution" at -1 -- matching Section 4.4 verbatim.

Source fit (the fit behind the paper figures):
    originalPolAn_results/fits/TBIPhier_ideal_ak_Nreg_all_joint_varfam_K25/

Outputs:
    docs/tab_topic_dictionary.tex   (LaTeX longtable, ready to \input)
and a console preview.
"""
import os
import numpy as np
import pandas as pd

REPO = os.path.dirname(os.path.abspath(__file__))
FIT = os.path.join(REPO, "..", "originalPolAn_results", "fits",
                   "TBIPhier_ideal_ak_Nreg_all_joint_varfam_K25", "params")
VOCAB_F = os.path.join(REPO, "..", "STBS_CAVI", "data", "hein-daily",
                       "clean", "vocabulary114.txt")
OUT_TEX = os.path.join(REPO, "docs", "tab_topic_dictionary.tex")

N_WORDS = 6   # terms per cell

# Labels aligned to the beta/eta ROW order of THIS fit (verified row-by-row
# against the neutral top terms; see header).
TOPIC_LABELS = [
    "National Security",                  # 0
    "Supreme Court",                      # 1
    "National Parks & Coast Guard",       # 2
    "Human Trafficking",                  # 3
    "Commemoration & Anniversaries",      # 4
    "Gun Violence",                       # 5
    "Middle Class & Small Business",      # 6
    "Health Care (ACA)",                  # 7
    "Public Health (Zika)",               # 8
    "Veterans & Health Care",             # 9
    "Drugs & Addiction",                  # 10
    "Climate Change",                     # 11
    "Natural Resources & Energy",         # 12
    "Planned Parenthood & Abortion",      # 13
    "National Institutes of Health",      # 14
    "Middle East & Nuclear Weapons",      # 15
    "Immigration & Homeland Security",    # 16
    "Social Security & Taxes",            # 17
    "Bipartisan Rhetoric",                # 18
    "Clean Water Act",                    # 19
    "Law Enforcement",                    # 20
    "Wars & Civil Rights",                # 21
    "Education for Children",             # 22
    "Cyber Security",                     # 23
    "Export, Import & Business",          # 24
]


def latex_escape(s):
    for a, b in [("&", r"\&"), ("_", r"\_"), ("%", r"\%"), ("#", r"\#")]:
        s = s.replace(a, b)
    return s


def top_terms(score, vocab, n):
    idx = np.argsort(score)[::-1][:n]
    return [vocab[i] for i in idx]


def main():
    vocab = np.array([l.strip() for l in open(VOCAB_F) if l.strip()])
    V = len(vocab)
    Eb = (pd.read_csv(os.path.join(FIT, "beta_shp.csv"), index_col=0) /
          pd.read_csv(os.path.join(FIT, "beta_rte.csv"), index_col=0)).to_numpy()
    eta = pd.read_csv(os.path.join(FIT, "eta_loc.csv"), index_col=0).to_numpy()
    K = Eb.shape[0]
    assert Eb.shape[1] == V == eta.shape[1], (Eb.shape, V, eta.shape)
    assert len(TOPIC_LABELS) == K, (len(TOPIC_LABELS), K)

    logb = np.log(Eb)
    rows = []
    for k in range(K):
        neutral = top_terms(logb[k], vocab, N_WORDS)              # ideal = 0
        liberal = top_terms(logb[k] - eta[k], vocab, N_WORDS)     # ideal = -1
        conserv = top_terms(logb[k] + eta[k], vocab, N_WORDS)     # ideal = +1
        rows.append((k, TOPIC_LABELS[k], neutral, liberal, conserv))

    # ---- console preview ----
    for k, lab, neu, lib, con in rows:
        print(f"\n[{k:2d}] {lab}")
        print(f"     neutral : {', '.join(neu)}")
        print(f"     ideal -1: {', '.join(lib)}")
        print(f"     ideal +1: {', '.join(con)}")

    # ---- LaTeX longtable ----
    L = []
    L.append(r"% Auto-generated by 25_topic_dictionary.py -- do not edit by hand.")
    L.append(r"% Topic dictionary: neutral / ideal=-1 (liberal) / ideal=+1 (conservative) terms.")
    hdr = (r"{\scriptsize\#} & \textbf{Topic} & \textbf{Neutral ($\ideal=0$)} & "
           r"\textbf{Liberal ($\ideal=-1$)} & \textbf{Conservative ($\ideal=+1$)}\\")
    L.append(r"\begin{footnotesize}")
    L.append(r"\begin{longtable}{@{}>{\raggedright\arraybackslash}p{0.035\textwidth}"
             r">{\raggedright\arraybackslash}p{0.175\textwidth}"
             r">{\raggedright\arraybackslash}p{0.245\textwidth}"
             r">{\raggedright\arraybackslash}p{0.245\textwidth}"
             r">{\raggedright\arraybackslash}p{0.245\textwidth}@{}}")
    L.append(r"\caption{Topic dictionary for the 25 estimated topics. For each "
             r"topic the table lists the most prevalent terms under a neutral "
             r"ideological position ($\ideal=0$) and the terms whose corrected "
             r"intensity is highest at a liberal ($\ideal=-1$) and a "
             r"conservative ($\ideal=+1$) position. Terms are ranked by the "
             r"ideology-adjusted log-intensity $\log\E[\beta_{kv}]+\ideal\cdot"
             r"\eta_{kv}$. The topic number (first column) matches the numbering "
             r"used throughout the main text and figures."
             r"\label{tab:topic_dictionary}}\\")
    L.append(r"\toprule")
    L.append(hdr)
    L.append(r"\midrule")
    L.append(r"\endfirsthead")
    L.append(r"\toprule")
    L.append(hdr)
    L.append(r"\midrule")
    L.append(r"\endhead")
    L.append(r"\bottomrule")
    L.append(r"\endfoot")
    for k, lab, neu, lib, con in rows:
        c0 = r"{\scriptsize %d}" % k
        c1 = r"\textbf{%s}" % latex_escape(lab)
        c2 = latex_escape(", ".join(neu))
        c3 = latex_escape(", ".join(lib))
        c4 = latex_escape(", ".join(con))
        L.append(f"{c0} & {c1} & {c2} & {c3} & {c4}\\\\")
        L.append(r"\addlinespace[2pt]")
    L.append(r"\end{longtable}")
    L.append(r"\end{footnotesize}")

    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"\n-> wrote {OUT_TEX}")
    print("   (requires \\ideal, \\E, \\eta macros + booktabs + longtable + array)")


if __name__ == "__main__":
    main()
